name: BetaKey
author: KeksDevelopment
version: 2.0.1
api: [3.0.0, 4.0.0]
main: KeksDevelopment\BetaKey\main
commands:
 betakeys:
  description: Manage the Beta-Keys on your Server!
  permission: "betakeys.ui"
 
permissions:
 betakeys.ui:
  default: op
 createkeys.ui:
  default: op
 deletekeys.ui:
  default: op
 listkeys.ui:
  default: op
